# This workflow bumps the version and release straight afterward
# it covers the situation for the releasing through conventional commits
name: Release with Conventional Commit
on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed
permissions:
  contents: write
jobs:
  tag-and-release:
    name: Tag And Release
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cashapp/activate-hermit@12a728b03ad41eace0f9abaf98a035e7e8ea2318 # cashapp/activate-hermit@v1
      - name: Push tag and Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: scripts/release.sh
